let songs = [
    {id: "musics-1", songName: "tu mehnat kar-affat", filePath: "songs/1.mp3", coverPath: "covers/1.jpg"},
    {id: "musics-5",songName: "Bewafa - nishyar", filePath: "songs/5.mp3", coverPath: "covers/5.jpg"},
    
    {id: "musics-9", songName: "geet hogi meri-honey singh", filePath: "songs/2.mp3", coverPath: "covers/9.jpg"},
    
    {id: "musics-11", songName: "garda udana tu mujhse sikho", filePath: "songs/11.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-14", songName: "e-watan watan awad rahe tu", filePath: "songs/14.mp3", coverPath: "covers/1.jpg"},
    {id: "musics-15", songName: "jo bhi hum karte he", filePath: "songs/15.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-16", songName: "hai mujhe vishwash-amit bhadana", filePath: "songs/16.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-17", songName: "clear iit-deno james", filePath: "songs/17.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-18", songName: "appna time aayega", filePath: "songs/18.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-19", songName: "nisne pe lagna jruri hai", filePath: "songs/19.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-21", songName: "2 Cielo - Huma-Huma", filePath: "songs/21.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-24", songName: "ab likhta hu plane me", filePath: "songs/24.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-25", songName: "kaam kaam acche se", filePath: "songs/25.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-26", songName: "duriyan-deno james", filePath: "songs/26.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-28", songName: "tujhe lagta hai tu har gya", filePath: "songs/28.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-29", songName: "2 Cielo - Huma-Huma", filePath: "songs/29.mp3", coverPath: "covers/2.jpg"},
    {id: "musics-30", songName: "Hussel-RCR ", filePath: "songs/30.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-31", songName: "ram raj", filePath: "songs/31.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-34", songName: "back banchers-2 ", filePath: "songs/34.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-37", songName: "rap shyari", filePath: "songs/37.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-38", songName: "looser-deno james", filePath: "songs/38.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-39", songName: "looser-deno james", filePath: "songs/39.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-40",songName: "hua dagabaz hai-RCR", filePath: "songs/40.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-43",songName: "ho gya wo preshan", filePath: "songs/43.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-44",songName: "bachpan se than liya", filePath: "songs/44.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-45",songName: "sabko dena jabab hai", filePath: "songs/45.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-47",songName: "dhakke dete log yehan per", filePath: "songs/47.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-48",songName: "khud ki ladayi ladte ja", filePath: "songs/48.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-49",songName: "chor de bahi bandi bazi", filePath: "songs/49.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-50",songName: "love you papa-RCR", filePath: "songs/50.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-51",songName: "prichay - amit bhadana", filePath: "songs/51.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-52",songName: "jayaj hai mera krodh", filePath: "songs/52.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-53",songName: "back banchers", filePath: "songs/53.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-54",songName: "asli wala marad", filePath: "songs/54.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-57",songName: "aayega tumhara dor kabhi", filePath: "songs/57.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-58",songName: "unstopable-deno james", filePath: "songs/58.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-59",songName: "vardan-carryminati", filePath: "songs/59.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-60",songName: "yaddieyen-deno james", filePath: "songs/60.m4a", coverPath: "covers/6.jpg"},
    {id: "musics-61",songName: "yaalgar", filePath: "songs/61.m4a", coverPath: "covers/6.jpg"},
    {id: "musics-62",songName: "abby-viral", filePath: "songs/62.m4a", coverPath: "covers/6.jpg"},    
]



let quotes = [
    {id: "quotes-0", quotespath: "covers/11.jpg"},
    {id: "quotes-1", quotespath: "covers/12.jpg"},
    {id: "quotes-2", quotespath: "covers/13.jpg"},
    {id: "quotes-3", quotespath: "covers/14.jpg"},
    {id: "quotes-6", quotespath: "covers/17.jpg"},
    {id: "quotes-7", quotespath: "covers/18.jpg"},
    {id: "quotes-8", quotespath: "covers/19.jpg"},
    {id: "quotes-9", quotespath: "covers/20.jpg"},
    {id: "quotes-0", quotespath: "covers/21.jpg"},
    {id: "quotes-1", quotespath: "covers/22.jpg"},
    {id: "quotes-2", quotespath: "covers/23.jpg"},
    {id: "quotes-3", quotespath: "covers/24.jpg"},
    {id: "quotes-4", quotespath: "covers/25.jpg"},
    {id: "quotes-5", quotespath: "covers/26.jpg"},
    {id: "quotes-6", quotespath: "covers/27.jpg"},
    {id: "quotes-7", quotespath: "covers/28.jpg"},
    {id: "quotes-8", quotespath: "covers/29.jpg"},
    {id: "quotes-9", quotespath: "covers/30.jpg"},
    {id: "quotes-0", quotespath: "covers/31.jpg"},
    {id: "quotes-1", quotespath: "covers/32.jpg"},
    {id: "quotes-2", quotespath: "covers/33.jpg"},
    {id: "quotes-3", quotespath: "covers/34.jpg"},
    {id: "quotes-4", quotespath: "covers/35.jpg"},
    {id: "quotes-5", quotespath: "covers/36.jpg"},
    {id: "quotes-6", quotespath: "covers/37.jpg"},
    {id: "quotes-7", quotespath: "covers/38.jpg"},
    {id: "quotes-8", quotespath: "covers/39.jpg"},
    {id: "quotes-9", quotespath: "covers/40.jpg"},
    {id: "quotes-0", quotespath: "covers/41.jpg"},
    {id: "quotes-1", quotespath: "covers/42.jpg"},
    {id: "quotes-2", quotespath: "covers/43.jpg"},
    {id: "quotes-3", quotespath: "covers/44.jpg"},
    {id: "quotes-4", quotespath: "covers/45.jpg"},
    {id: "quotes-5", quotespath: "covers/46.jpg"},
    {id: "quotes-6", quotespath: "covers/47.jpg"},
    {id: "quotes-7", quotespath: "covers/48.jpg"},
    {id: "quotes-8", quotespath: "covers/49.jpg"},
    {id: "quotes-9", quotespath: "covers/50.jpg"},
    {id: "quotes-9", quotespath: "covers/51.jpg"},
    {id: "quotes-1", quotespath: "covers/52.jpg"},
    {id: "quotes-2", quotespath: "covers/53.jpg"},
    {id: "quotes-3", quotespath: "covers/54.jpg"},
    {id: "quotes-4", quotespath: "covers/55.jpg"},
    {id: "quotes-5", quotespath: "covers/56.jpg"},
    {id: "quotes-6", quotespath: "covers/57.jpg"},
]