let songs = [
    {id: "musics-1", songName: "tu mehnat kar-affat", filePath: "songs/1.mp3", coverPath: "covers/1.jpg"},
    {id: "musics-2", songName: "koshis karne walo ki", filePath: "songs/2.mp3", coverPath: "covers/2.jpg"},
    {id: "musics-3", songName: "strong motivation", filePath: "songs/3.mp3", coverPath: "covers/3.jpg"},
    {id: "musics-4",songName: "motivation quotes", filePath: "songs/4.mp3", coverPath: "covers/4.jpg"},
    {id: "musics-5",songName: "Bewafa - nishyar", filePath: "songs/5.mp3", coverPath: "covers/5.jpg"},
    {id: "musics-6",songName: "kisto pe car - nishyar", filePath: "songs/2.mp3", coverPath: "covers/6.jpg"},
    {id: "musics-7",songName: "erade ki diwar meri abby-viral", filePath: "songs/2.mp3", coverPath: "covers/7.jpg"},
    {id: "musics-8", songName: "muskilo karke ke assan", filePath: "songs/2.mp3", coverPath: "covers/8.jpg"},
    {id: "musics-9", songName: "geet hogi meri-honey singh", filePath: "songs/2.mp3", coverPath: "covers/9.jpg"},
    {id: "musics-10", songName: "muskil manjil ban jayegi", filePath: "songs/4.mp3", coverPath: "covers/10.jpg"},
    {id: "musics-11", songName: "garda udana tu mujhse sikho", filePath: "songs/11.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-13", songName: " 1 Warriyo - Mortals [NCS Release]", filePath: "songs/12.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-14", songName: "e-watan watan awad rahe tu", filePath: "songs/13.mp3", coverPath: "covers/1.jpg"},
    {id: "musics-15", songName: "jo bhi hum karte he", filePath: "songs/14.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-16", songName: "hai mujhe vishwash-amit bhadana", filePath: "songs/15.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-17", songName: "clear iit-deno james", filePath: "songs/16.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-18", songName: "appna time aayega", filePath: "songs/17.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-19", songName: "nisne pe lagna jruri hai", filePath: "songs/18.m4a", coverPath: "covers/1.jpg"},
    {id: "musics-20", songName: "back banchers", filePath: "songs/19.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-21", songName: "2 Cielo - Huma-Huma", filePath: "songs/20.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-22", songName: "laga hu dharne-deno james", filePath: "songs/21.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-23", songName: "tu baag hai mera", filePath: "songs/23.mp3", coverPath: "covers/2.jpg"},
    {id: "musics-24", songName: "ab likhta hu plane me", filePath: "songs/24.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-25", songName: "kaam kaam acche se", filePath: "songs/25.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-26", songName: "duriyan-deno james", filePath: "songs/26.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-27", songName: "rap compitation", filePath: "songs/27.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-28", songName: "tujhe lagta hai tu har gya", filePath: "songs/28.m4a", coverPath: "covers/2.jpg"},
    {id: "musics-29", songName: "2 Cielo - Huma-Huma", filePath: "songs/29.mp3", coverPath: "covers/2.jpg"},
    {id: "musics-30", songName: "Hussel-RCR ", filePath: "songs/30.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-31", songName: "ram raj", filePath: "songs/31.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-34", songName: "back banchers-2 ", filePath: "songs/34.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-35", songName: "kon hun me", filePath: "songs/35.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-36", songName: "tujhe aab ye dikhna h", filePath: "songs/36.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-37", songName: "rap shyari", filePath: "songs/37.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-38", songName: "looser-deno james", filePath: "songs/38.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-39", songName: "looser-deno james", filePath: "songs/39.m4a", coverPath: "covers/3.jpg"},
    {id: "musics-40",songName: "hua dagabaz hai-RCR", filePath: "songs/40.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-41",songName: "muskilo ke mar ke-nishyar", filePath: "songs/41.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-42",songName: "zindgi tang", filePath: "songs/42.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-43",songName: "ho gya wo preshan", filePath: "songs/43.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-44",songName: "bachpan se than liya", filePath: "songs/44.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-45",songName: "sabko dena jabab hai", filePath: "songs/45.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-47",songName: "dhakke dete log yehan per", filePath: "songs/47.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-48",songName: "khud ki ladayi ladte ja", filePath: "songs/48.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-49",songName: "chor de bahi bandi bazi", filePath: "songs/49.m4a", coverPath: "covers/4.jpg"},
    {id: "musics-50",songName: "love you papa-RCR", filePath: "songs/50.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-51",songName: "prichay - amit bhadana", filePath: "songs/51.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-52",songName: "jayaj hai mera krodh", filePath: "songs/52.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-53",songName: "back banchers", filePath: "songs/53.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-54",songName: "asli wala marad", filePath: "songs/54.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-57",songName: "aayega tumhara dor kabhi", filePath: "songs/57.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-58",songName: "unstopable-deno james", filePath: "songs/58.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-59",songName: "vardan-carryminati", filePath: "songs/59.m4a", coverPath: "covers/5.jpg"},
    {id: "musics-60",songName: "yaddieyen-deno james", filePath: "songs/60.m4a", coverPath: "covers/6.jpg"},
    {id: "musics-61",songName: "yaalgar", filePath: "songs/61.m4a", coverPath: "covers/6.jpg"},
    {id: "musics-62",songName: "abby-viral", filePath: "songs/62.m4a", coverPath: "covers/6.jpg"},
    {id: "musics-63",songName: "mahakal", filePath: "songs/63.m4a", coverPath: "covers/6.jpg"},
    
]